{
 "title": "Airflow dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "airflow_id", "label": "Airflow Instance Id", "query": "label_values(airflow_id)" }
  ]
 },
 "panels": [
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_heartbeat{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Dagbag size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_dagbag_size{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "DAG processing total parse time",
   "type": "stat",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_total_parse_time{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "stat",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Zombies killed",
   "type": "stat",
   "description": "Zombie tasks killed",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_zombies_killed{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor running tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_executor_running_tasks{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Operator failure rate per minute",
   "type": "timeseries",
   "description": "Total failures of given operator",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_operator_failures_BatchOperator + airflow_operator_failures_PythonOperator + airflow_operator_failures_ShortCircuitOperator",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Total failed tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_ti_failures{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs started per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "airflow_job_start", "legendFormat": "{{job_name}}" }
   ]
  },
  {
   "title": "Executor open slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_executor_open_slots{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor queued tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_executor_queued_tasks{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "DAG stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Success DAG run duration",
   "type": "timeseries",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success_sum{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Failed DAG run count",
   "type": "timeseries",
   "description": "Seconds taken for a DagRun to reach failed state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_failed_count{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "timeseries",
   "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (dag_id, quantile) (airflow_dagrun_duration_success_sum{airflow_id=\"$airflow_id\"}) ",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  }
 ]
}